AWS:
  AwsAKey : "AKIAQBUXGDZ4F3SHTW5S"
  AwsSKey : "1oGCi1R5bVvnyCFAixZA1UuTz2JfTHP75951J7/B"
  
sfdc:
  username: "shubham.k.bhosale@apisero.com"
  password: "Shubham@1522"
  token: "vBzlwGhcGCSEsJtG2CImtujJ"
  
Email:
  host : "smtp.gmail.com"
  username : "ecom.express.batch39@gmail.com"
  port : "465"
  password : "Ecom@batch39"
  
DB:
  host : "sql6.freemysqlhosting.net"
  username : "sql6452759"
  port : "3306"
  password : "JC12vdYHte"
  database : "sql6452759"
  
http:
  host : "0.0.0.0"
  port : "8081"
  
  
