{
  "bucketName": "ecommercebatch39",
  "sseAlgorithm": null,
  "ongoingRestore": false,
  "storageClass": null,
  "sseCustomerAlgorithm": null,
  "contentDisposition": null,
  "contentEncoding": null,
  "contentType": "text/csv",
  "key": "inventory.csv",
  "sseCustomerKeyMd5": null,
  "contentMD5": null,
  "requesterCharged": false,
  "replicationStatus": null,
  "cacheControl": null,
  "httpExpiresDate": null,
  "sseAwsKmsKeyId": null,
  "versionId": null,
  "restoreExpirationTime": null,
  "expirationTimeRuleId": null,
  "expirationTime": null,
  "contentLanguage": null,
  "contentLength": 110,
  "etag": "41e48bb65e73f759f20ca08fc152fc64",
  "lastModified": |2021-11-15T15:27:07|,
  "userMetadata": {},
  "redirectLocation": null
}